feat: 리뷰 Entity 구현
p-ser/p-ser-backend pull request #10
Opened 2024-04-17 05:47 UTC by iwantPark

### 개요
-  추가한 기능 
1. 리뷰 이미지
2. 닉네임
3. 글 생성, 수정 날짜 추가
4. 삭제 여부 필드
5. 별점 

### 변경사항

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KAN-89](https://kakaoproject3.atlassian.net/browse/KAN-89)

### 팀원들에게 하고 싶은 말
- 검토 후 approve 부탁드립니다

2024-04-17 06:50 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
>      @ManyToOne(fetch = FetchType.LAZY)
- ERD 상에서는 일대다로 설계되어 있었지만 예약 당 한 리뷰가 낫지 않을까요?
- 연관관계 어노테이션 옵션으로 "cascade = {CascadeType.PERSIST}, fetch = FetchType.LAZY, optional = false" 도 들어갔으면 좋겠습니다

2024-04-17 06:52 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
>          // 넣은 Reservation에 나를 add 추가해준다.
현재 단방향이니 편의메소드는 필요 없을 듯 합니다

2024-04-17 06:55 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
>      @Builder
BaseEntity의 필드들은 모두 자동으로 생성되는 필드들이니 "Long id, LocalDateTime createdAt, LocalDateTime updatedAt" 의 인자로 받을 필요가 없습니다

2024-04-17 07:16 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
>      private String grade;
enum 타입으로 하는 편이 좋을 것 같습니다

2024-04-17 07:46 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
>          // 넣은 Reservation에 나를 add 추가해준다.
넵!

2024-04-17 07:46 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
>      @Builder
수정 하였습니당

2024-04-17 11:35 UTC, amanecopse requested changes

2024-04-17 11:35 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Review.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST, optional = false)
ERD는 일대다로 되어있지만 배민리뷰처럼 예약 건 당 리뷰 하나로 일대일이 좋을 것 같습니다
OneToOne으로 하고 unique=true 옵션을 추가하면 어떨까요

2024-04-18 05:58 UTC, uiheonn approved these changes

2024-04-18 05:59 UTC, amanecopse approved these changes

2024-04-18 06:00 UTC, merged