[KSP-129] RoomApi 리팩토링 및 RoomService 임시 구현
p-ser/p-ser-backend pull request #16
Opened 2024-04-19 04:29 UTC by wooyong99

### 개요
- RoomApi 리팩토링 및 RoomService 임시 구현

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-125](https://kakaoproject3.atlassian.net/browse/KSP-125)

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-04-19 06:29 UTC, iwantPark approved these changes

2024-04-29 00:51 UTC, amanecopse requested changes

2024-04-29 00:51 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/api/RoomApi.java
> +    public ResponseEntity<ApiResponse<Void>> roomDelete(@PathVariable Long hotelId, @PathVariable Long roomId,
path param도 원시타입으로하는게 좋을 것 같습니다

2024-04-29 00:51 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/application/RoomService.java
> +        Hotel hotel = findHotelByIdAndUserId(request.getHotelId(), userId);
따로 인가 로직을 @PreAuthorize 어노테이션으로 분리하는 게 좋을 것 같습니다

2024-04-29 00:51 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/application/RoomService.java
> +        Room room = roomDao.findByIdAndHotelId(roomId, hotel.getId()).orElseThrow(() -> new IllegalArgumentException());
400으로 throw 될 텐데
404가 낫지 않나요?

2024-04-29 00:51 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Room.java
> +        if (!request.getName().equals(name)) {
굉장히 보일러 플레이트 코드가 길어져서 유지보수가 힘들 것 같은데 mapstruct 업데이트 자동 생성을 써보는 건 어떨까요?

2024-04-29 01:05 UTC, wooyong99 commented on src/main/java/com/pser/hotel/domain/hotel/api/RoomApi.java
> +    public ResponseEntity<ApiResponse<Void>> roomDelete(@PathVariable Long hotelId, @PathVariable Long roomId,
수정하겠습니다 !

2024-04-29 08:08 UTC, merged