[KSP-112]  ReviewController 구현
p-ser/p-ser-backend pull request #19
Opened 2024-04-29 02:24 UTC by iwantPark

### 개요
- [KSP-112] ReviewController 구현
  
- [KSP-112] ReviewApi Test코드 작성

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-112] (https://kakaoproject3.atlassian.net/browse/KSP-112)

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-04-29 08:29 UTC, amanecopse requested changes

2024-04-29 08:29 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/dto/ReviewListResponseDto.java
> +    private List<ReviewDto> reviews;
Slice나 Page 객체로 래핑하지 않고 따로 리스트 Dto를 만드신 이유가 있으실까요?
Slice나 Page를 쓰면 JPA 호환이나 제공 기능이 좋아서 편할 것 같아요

2024-04-29 08:29 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/dto/ReviewRequestDto.java
> +public class ReviewRequestDto {
현재 DTO 네이밍 컨벤션으로
~Request: Request body 또는 Request parameter 에 들어가는 DTO
~Response: 반환 데이터로 들어가는 DTO
~Dto: 그 외에 계층 간 함수 호출 시 데이터 전송을 위한 DTO
로 구분지어 사용하고 있습니다.
해당 클래스는 ReviewRequest 라고 명명하는 것이 좋을 듯 합니다

2024-04-29 08:29 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/api/ReviewApi.java
> +        return ResponseEntity.created(URI.create("/reviews/" + createdReviewId))
created()에서 이미 인자로 생성 리소스 위치를 반환 헤더 정보로서 전해주고 있기 때문에 반환 body 없이 하심이 Restful 하지 않을까 싶습니다.

2024-04-30 01:43 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/dto/ReviewRequestDto.java
> +public class ReviewRequestDto {
넵!

2024-05-01 00:50 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/dto/ReviewListResponseDto.java
> +    private List<ReviewDto> reviews;
넵!

2024-05-07 00:05 UTC, amanecopse approved these changes

2024-05-07 00:21 UTC, wooyong99 approved these changes
고생하셨습니다 !:)

2024-05-07 00:22 UTC, wooyong99 approved these changes
고생하셨습니다 ! :)

2024-05-07 01:57 UTC, merged