Feature/ksp 149/refactor room
p-ser/p-ser-backend pull request #20
Opened 2024-04-30 03:40 UTC by wooyong99

### 개요
- Room 생성 시 , RoomImage 저장 기능 구현
 
### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-149](https://kakaoproject3.atlassian.net/browse/KSP-149)

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-04-30 06:37 UTC, amanecopse requested changes

2024-04-30 06:37 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Room.java
> +    public void update(RoomRequest request) {
이거 또 들어가 있네요

2024-05-02 02:31 UTC, uiheonn approved these changes
훌륭하군요 고생하셨습니다

2024-05-07 00:11 UTC, iwantPark approved these changes

2024-05-07 00:25 UTC, wooyong99 commented on src/main/java/com/pser/hotel/domain/hotel/domain/Room.java
> +    public void update(RoomRequest request) {
수정했습니다 ! :)

2024-05-07 01:58 UTC, amanecopse approved these changes

2024-05-07 01:58 UTC, merged