[KSP-113] 숙소 Dao 구현
p-ser/p-ser-backend pull request #21
Opened 2024-05-02 01:09 UTC by uiheonn

### 개요
- Dto 수정
- Hotel Dao 생성
- User Dao 생성
- Facility Dao 생성
- QueryDsl을 통해 숙소 검색 기능 구현
- Dao 및 검색 기능 테스트 코드 구현

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-113]

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-05-02 02:09 UTC, amanecopse requested changes

2024-05-02 02:09 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
> +            .selectFrom(QHotel.hotel)
이 후에 .stream().map()으로 Dto 객체 매핑을 해주던데
그렇다면 애초에 select에서 Dto 객체 프로젝션을 해주는게 낫지 않나요?

2024-05-02 02:09 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
> +        HotelResponse hotelResponse = new HotelResponse();
entity to dto 매핑 함수가 필요하시다면 Sample 코드의 mapstruct 사용 부분을 참고하시면 좋을 것 같습니다
필드수만큼 매핑에 필요한 많은 보일러플래이트 코드들을 자동생성해주기 때문에 유지보수가 편해집니다

2024-05-02 04:35 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
> +        queryFactory = new JPAQueryFactory(em);
QuerydslRepositorySupport를 상속받아 로직을 구현하였는데, 상속받기 위해선 디폴트 생성자가 필요하여 생성했습니다. 하지만 확인해보니 QuerydslRepositorySupport를 상속받지 않아도 문제가 없네요. 생성자 코드는 지우도록 하겠습니다.

2024-05-02 05:04 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
> +            .selectFrom(QHotel.hotel)
selectFrom말고 select와 from으로 나누어서 할 수 있군요... 감사합니다

2024-05-02 05:45 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/dao/HotelDaoImpl.java
> +        HotelResponse hotelResponse = new HotelResponse();
넵!

2024-05-02 08:38 UTC, amanecopse approved these changes

2024-05-07 00:10 UTC, iwantPark approved these changes
수고하셨습니다

2024-05-07 00:10 UTC, merged