[KSP 147] EntityImages 추가
p-ser/p-ser-backend pull request #23
Opened 2024-05-03 07:52 UTC by iwantPark

### 개요
- domain에 ReviewImageFile 클래스 생성
- Review에 OneToMany 관계로 추가

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-147]

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-05-07 00:12 UTC, amanecopse requested changes

2024-05-07 00:12 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImageFile.java
> +    @JoinColumn(name = "review_id")
위 아래에 각각 nullable, optional 로 false 넣었으면 좋겠습니다

2024-05-07 00:12 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImageFile.java
> +    public ReviewImageFile(String fileName, String filePath, Review review) {
빌더가 있었으면 좋겠습니다

2024-05-07 00:12 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImageFile.java
> +public class ReviewImageFile {
다른 이미지 엔티티들의 명명처럼 ReviewImage라고 하면 어떨까요?

2024-05-07 03:45 UTC, uiheonn approved these changes
고생하셨습니다

2024-05-07 08:00 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImageFile.java
> +    @JoinColumn(name = "review_id")
넵!

2024-05-07 08:00 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImageFile.java
> +    public ReviewImageFile(String fileName, String filePath, Review review) {
넵

2024-05-07 08:00 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/domain/ReviewImageFile.java
> +public class ReviewImageFile {
수정했습니다

2024-05-08 00:25 UTC, amanecopse commented
충돌해결 부탁드립니다

2024-05-08 05:59 UTC, amanecopse approved these changes

2024-05-08 05:59 UTC, merged