[KSP-154] 숙소 Service 구현
p-ser/p-ser-backend pull request #24
Opened 2024-05-07 00:49 UTC by uiheonn

### 개요
- Controller 리턴 값 리팩토링
- map struct 사용을 위해 mapper 클래스 생성
- service 코드 구체화
- service 테스트 코드 작성

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-154]

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-05-07 02:11 UTC, amanecopse requested changes

2024-05-07 02:11 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
> +        facilityDao.save(facility);
Entity 구현을 살펴보건데 Hotel -> Facility 로의 Persist cascade가 있으니 hotel만 save해도 될 듯 합니다

2024-05-07 02:11 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
> +            .orElseThrow(() -> new IllegalArgumentException("not found hotel"));
not found에 맞는 오류를 던지는 것이 좋아보입니다
해당 오류에 경우 400이 던져지므로 404를 던지는 오류 클래스를 사용함이 좋을듯합니다
그 외 다수 이에 해당되는 코드가 있는 것으로 보입니다

2024-05-07 02:11 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/api/HotelApi.java
>      @PatchMapping("/{hotelId}") // 숙소 수정
수정, 삭제 API에 경우 리소스에 대한 주인임을 식별하기 위해 @Preauthorize 어노테이션을 통한 권한 인가 로직이 필요해 보입니다
밑에 delete 도 동일합니다

2024-05-07 05:03 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
> +        facilityDao.save(facility);
넵 알겠습니다

2024-05-07 05:03 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/application/HotelService.java
> +            .orElseThrow(() -> new IllegalArgumentException("not found hotel"));
감사합니다

2024-05-07 05:04 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/api/HotelApi.java
>      @PatchMapping("/{hotelId}") // 숙소 수정
넵!

2024-05-07 07:59 UTC, amanecopse approved these changes

2024-05-08 01:56 UTC, iwantPark approved these changes
수고하셨습니당

2024-05-08 05:51 UTC, merged