[KSP-153] 예약 API 구현
p-ser/p-ser-backend pull request #25
Opened 2024-05-09 05:15 UTC by givemea1

### 개요
- 예약 controller, service, dao 구현

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-153]

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다.

2024-05-10 02:23 UTC, ChoiHyebin approved these changes
👍🏻

2024-05-10 02:35 UTC, amanecopse requested changes

2024-05-10 02:35 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/api/ReservationApi.java
> +    @PostMapping("/save")
Post, Patch, Delete 등의 HTTP Method 들은 이미 기능을 내포하고 있기 때문에 굳이  경로에 save, update, delete 같은 라우팅을 명시할 필요가 없습니다

2024-05-10 02:35 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/domain/Reservation.java
> +    public void updateInformation(ReservationUpdateRequestDto reservationUpdateRequestDto){
엔티티 안에 업데이트 함수를 따로 만들지 않고 mapstruct 라이브러리가 제공하는 매핑 인터페이스로 자동으로 업데이트 함수를 만드는 걸 추천합니다

2024-05-10 02:35 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/dto/reservation/request/ReservationSaveRequestDto.java
> +public class ReservationSaveRequestDto {
DTO에 제약조건이 하나도 없는데 필수 필드나 제약조건이 필요한 필드에 대해 제약조건 어노테이션을 붙이고 컨트롤러 쪽에는 @Validated 어노테이션을 붙여 API 요청시 Request body를 자동으로 검증하도록 하는 방법이 좋을 것 같습니다

2024-05-20 01:18 UTC, uiheonn commented on src/main/java/com/pser/hotel/domain/hotel/domain/Reservation.java
> +    public void updateInformation(ReservationUpdateRequestDto reservationUpdateRequestDto){
죄송합니다 제가 수정해야하는 부분인걸 이제 확인했습니다... 피드백 감사합니다! 수정해서 올리겠습니다

2024-05-20 02:30 UTC, givemea1 commented on src/main/java/com/pser/hotel/domain/hotel/api/ReservationApi.java
> +    @PostMapping("/save")
수정했습니다.

2024-05-20 02:30 UTC, givemea1 commented on src/main/java/com/pser/hotel/domain/hotel/domain/Reservation.java
> +    public void updateInformation(ReservationUpdateRequestDto reservationUpdateRequestDto){
수정했습니다.

2024-05-20 08:32 UTC, uiheonn approved these changes

2024-05-20 10:06 UTC, givemea1 commented on src/main/java/com/pser/hotel/domain/hotel/dto/reservation/request/ReservationSaveRequestDto.java
> +public class ReservationSaveRequestDto {
수정했습니다,

2024-05-21 00:46 UTC, amanecopse approved these changes

2024-05-21 00:50 UTC, merged