[KSP-207] Review DAO 기능 추가
p-ser/p-ser-backend pull request #36
Opened 2024-05-24 07:59 UTC by iwantPark

### 개요
- 작업 사항
1. dao 기능 추가 
2. ReviewDaoImpl 외 연동된 클래스 수정

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KSP-207]

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-05-26 06:50 UTC, amanecopse requested changes

2024-05-26 06:50 UTC, amanecopse commented on src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDaoCustom.java
> +    Page<Review> search(ReviewSearchRequest request, SearchQuery searchQuery, Pageable pageable);
ReviewSearchRequest 가 SearchQuery를 상속 안 받으면 공통 검색 파라미터를 받기 위해 SearchQuery 객체도 따로받아야 되겠지만 ReviewSearchRequest 을 보니 SearchQuery를 상속하고 있네요.
SearchQuery를 상속하고 있으니까 따로 SearchQuery를 인자로 받을 필요없이 
"Page<Review> search(ReviewSearchRequest request, Pageable pageable);" 로 작성해도 될 것 같아요

2024-05-27 03:36 UTC, wooyong99 approved these changes
고생하셨습니다 ! :)

2024-05-27 04:15 UTC, uiheonn approved these changes

2024-05-30 02:25 UTC, iwantPark commented on src/main/java/com/pser/hotel/domain/hotel/dao/ReviewDaoCustom.java
> +    Page<Review> search(ReviewSearchRequest request, SearchQuery searchQuery, Pageable pageable);
수정 완료하였습니다

2024-05-30 08:22 UTC, amanecopse approved these changes

2024-05-30 08:23 UTC, merged