[KSP-64] 숙박업소, 숙박업소 이밎, 숙박업소시설, 유저, 프로필 엔티티 실제 구현
p-ser/p-ser-backend pull request #6
Opened 2024-04-15 05:28 UTC by wooyong99

### 개요
- 즐겨찾기 API 무한스크롤로 구현

### 변경사항
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

### 관련 지라
[KAN-num](https://kaclga.atlassian.net/browse/KAN-num)

### 팀원들에게 하고 싶은 말
- 빠른 approve 부탁드립니다

2024-04-15 06:09 UTC, amanecopse requested changes

2024-04-15 07:19 UTC, wooyong99 commented on src/main/java/com/psear/hotel/domain/hotel/domain/Hotel.java
>      public void removeImage(HotelImage image){
피드백 수정했습니다 !

2024-04-15 07:19 UTC, wooyong99 commented on src/main/java/com/psear/hotel/domain/hotel/domain/Hotel.java
>      @ManyToOne(cascade = {CascadeType.PERSIST}, fetch = FetchType.LAZY)
피드백 수정했습니다 !

2024-04-15 07:20 UTC, wooyong99 commented on src/main/java/com/psear/hotel/domain/hotel/domain/HotelCategoryConverter.java
> +public class HotelCategoryConverter implements AttributeConverter<HotelCategoryEnum, String> {
변수 값 name -> value로 수정 후, Database Column 타입도 Integer로 수정하였습니다 !

2024-04-16 00:01 UTC, givemea1 approved these changes
ok

2024-04-16 00:05 UTC, amanecopse approved these changes

2024-04-16 00:06 UTC, merged